# tensor 的定义

In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


In [3]:
a = torch.Tensor(2,3)
print(a)
print(a.type())

tensor([[2.2688e-36, 1.2836e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.FloatTensor


In [4]:
a = torch.ones(2,2)
print(a)
print(a.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [5]:
a = torch.eye(2,2)
print(a)
print(a.type())

tensor([[1., 0.],
        [0., 1.]])
torch.FloatTensor


In [6]:
a = torch.zeros(2,2)
print(a)
print(a.type())

tensor([[0., 0.],
        [0., 0.]])
torch.FloatTensor


In [7]:
b = torch.Tensor(2,3)
a = torch.zeros_like(b)
print(a)
print(a.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [8]:
a = torch.ones_like(b)
print(a)
print(a.type())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [9]:
a = torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.9519, 0.3809, 0.5781],
        [0.1839, 0.3309, 0.9875]])
torch.FloatTensor


In [10]:
# 正态分布型
a = torch.normal(mean=0.0,std=torch.rand(5))
print(a)
print(a.type())

tensor([-1.3848,  0.4872,  0.5111, -1.6631, -0.0575])
torch.FloatTensor


In [11]:
a=torch.rand(5)
print(a)
print(a.type())

tensor([0.1446, 0.1296, 0.4687, 0.3916, 0.3564])
torch.FloatTensor


In [12]:
a=torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.7582, 0.3397, 0.8885],
        [0.2308, 0.4218, 0.8518]])
torch.FloatTensor


In [13]:
# 均匀分布
a = torch.Tensor(2,2).uniform_(-1,1)
print(a)
print(a.type())

tensor([[-0.6711,  0.3160],
        [-0.6239,  0.9062]])
torch.FloatTensor


In [14]:
# 序列生成
# 从0到10，以步长 3 递增，直到小于 11 的数字序列
a = torch.arange(0,11,3)
print(a)
print(a.type())

tensor([0, 3, 6, 9])
torch.LongTensor


In [15]:
# 2到10之间取等间隔的4个数
a = torch.linspace(2,10,4)
print(a)
print(a.type())

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
torch.FloatTensor


In [16]:
# 对样本进行随机打乱
a = torch.randperm(5)
b = torch.randperm(10)
print("a:",a)
print("b:",b)
print("a.type():",a.type())
print("b.type():",b.type())

a: tensor([1, 4, 2, 3, 0])
b: tensor([8, 1, 9, 4, 7, 3, 0, 6, 2, 5])
a.type(): torch.LongTensor
b.type(): torch.LongTensor


# tensor 属性
每一个Tensor都有数据类型（torch.dtype）和设备（torch.device）、内存布局（torch.layout)这三个属性。设备：在CPU还是在个GPU（cuda:0,1,2...)内存布局：是稠密（在内存中表示的是一块连续的存储空间）还是稀疏（在内存中表示的不是一块连续的存储空间，而是由多个不连续的存储空间组成的）

In [17]:
# 创建一个稠密张量并指定数据类型、设备和内存布局
a = torch.tensor([1,2,3],dtype=torch.float32,device=torch.device('cpu'))
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


## 创建一个稀疏张量
坐标值（indices）和对应的值（values）

In [18]:
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor


In [19]:
# 转成稠密张量打印
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())
y = torch.sparse_coo_tensor(indices,values,[3,4]).to_dense()
print(y)
print(y.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor
tensor([[0, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 0]])
torch.LongTensor


# tensor 算术运算

In [20]:
# add or sub
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a+b:",a+b)
print("a.add(b):",a.add(b))
print("torch.add(a,b):",torch.add(a,b))
print("a.add_(b):",a.add_(b))
print("a:",a)

a: tensor([[0.6889, 0.9506, 0.3247],
        [0.9136, 0.1913, 0.9883]])
b: tensor([[0.3190, 0.3258, 0.2886],
        [0.0099, 0.4565, 0.2185]])
a+b: tensor([[1.0079, 1.2764, 0.6133],
        [0.9235, 0.6477, 1.2068]])
a.add(b): tensor([[1.0079, 1.2764, 0.6133],
        [0.9235, 0.6477, 1.2068]])
torch.add(a,b): tensor([[1.0079, 1.2764, 0.6133],
        [0.9235, 0.6477, 1.2068]])
a.add_(b): tensor([[1.0079, 1.2764, 0.6133],
        [0.9235, 0.6477, 1.2068]])
a: tensor([[1.0079, 1.2764, 0.6133],
        [0.9235, 0.6477, 1.2068]])


In [21]:
# mul 乘（形状要相同）
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a*b:",a*b)
print("a.mul(b):",a.mul(b))
print("torch.mul(a,b):",torch.mul(a,b))
print("a.mul_(b):",a.mul_(b))
print("a:",a)

a: tensor([[0.9004, 0.0050, 0.5901],
        [0.1243, 0.2591, 0.2973]])
b: tensor([[0.0374, 0.1154, 0.4504],
        [0.4118, 0.2772, 0.9174]])
a*b: tensor([[0.0336, 0.0006, 0.2658],
        [0.0512, 0.0718, 0.2727]])
a.mul(b): tensor([[0.0336, 0.0006, 0.2658],
        [0.0512, 0.0718, 0.2727]])
torch.mul(a,b): tensor([[0.0336, 0.0006, 0.2658],
        [0.0512, 0.0718, 0.2727]])
a.mul_(b): tensor([[0.0336, 0.0006, 0.2658],
        [0.0512, 0.0718, 0.2727]])
a: tensor([[0.0336, 0.0006, 0.2658],
        [0.0512, 0.0718, 0.2727]])


In [22]:
# pow
a = torch.Tensor([1,2])
print("a**3:",a**3)
print("a.pow(3):",a.pow(3))
print("torch.pow(a,3):",torch.pow(a,3))
print("a.pow_(3):",a.pow_(3))

a**3: tensor([1., 8.])
a.pow(3): tensor([1., 8.])
torch.pow(a,3): tensor([1., 8.])
a.pow_(3): tensor([1., 8.])


In [23]:
# exp log sqrt
a = torch.tensor([1,2],dtype=torch.float32)
print("a.exp():",a.exp())
print("a.exp_():",a.exp_())
print("torch.exp(a):",torch.exp(a))
print("torch.exp_(a):",torch.exp_(a))

a.exp(): tensor([2.7183, 7.3891])
a.exp_(): tensor([2.7183, 7.3891])
torch.exp(a): tensor([  15.1543, 1618.1781])
torch.exp_(a): tensor([  15.1543, 1618.1781])


# tensor 矩阵运算

In [24]:
# matmul
a = torch.rand(2,3)
b = torch.rand(3,2)
print("a@b:",a@b)
print("a.matmul(b):",a.matmul(b))
print("torch.matmul(a,b):",torch.matmul(a,b))
print("a.matmul(b):",a.mm(b))
print("torch.matmul(a,b):",torch.mm(a,b))

a@b: tensor([[0.7179, 1.2364],
        [0.1177, 0.3025]])
a.matmul(b): tensor([[0.7179, 1.2364],
        [0.1177, 0.3025]])
torch.matmul(a,b): tensor([[0.7179, 1.2364],
        [0.1177, 0.3025]])
a.matmul(b): tensor([[0.7179, 1.2364],
        [0.1177, 0.3025]])
torch.matmul(a,b): tensor([[0.7179, 1.2364],
        [0.1177, 0.3025]])


# 高维tensor

In [25]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(a.matmul(b).shape)
# torch.Size([1, 2, 3, 3])

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
torch.Size([1, 2, 3, 3])


# in-place 操作
形如 x = x + y 不产生新的变量，还有上面的add_ sub_ mul_ pow_等等

# 广播机制
需要满足的两个条件：
1. 每个张量至少有一个维度
2. 两个张量的维度从最右边开始逐个比较，最右侧维度需要相等，前面维度用1补齐，最终维度：两个张量每一维二者取最大
第13个视频 6:30秒

# Tensor的取整/取余运算
.floor() 向下取整数
.ceil() 向上取整数
round() 四舍五入 >=0.5向上取整,<0.5向下取整
.trunc() 裁剪,只取整数部分
.frac() 只取小数部分
% 取余

In [26]:
a = torch.rand(2,2)
a = a * 10 #将rand生成的0-1之间的数转为1-10之间的数
print(a)
print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a%2)

tensor([[2.5859, 2.6846],
        [1.8402, 8.1867]])
tensor([[2., 2.],
        [1., 8.]])
tensor([[3., 3.],
        [2., 9.]])
tensor([[3., 3.],
        [2., 8.]])
tensor([[2., 2.],
        [1., 8.]])
tensor([[0.5859, 0.6846],
        [0.8402, 0.1867]])
tensor([[0.5859, 0.6846],
        [1.8402, 0.1867]])


# Tensor的比较运算
torch.eq(input, other, out=None) # 按每个成员进行等式操作,相同返回True或者false，类型是tensor
torch.equal(tensor1, tensor2)    # 如果tensor1和tensor2有相同的 size和elements,则为true
torch.ge(input, other, out=None) # input> = other
torch.gt(input, other, out=None) # input>other
torch.le(input, other, out=None) # input= < other
torch.It(input, other, out=None) # input<other
torch.ne(input, other, out=None) # input != other 不等于
# Tensor的取前k大/前k小/第k小的数值及其索引
torch.sort(input, dim=None, descending=False, out=None) #xf 目标input进行排序
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None)#沿着指定维度返回==最大==k个数值及其索引值
torch.kthvalue(input, k, dim=None, out=None)  #沿着指定维度返回第k个==最小==值及其索引值
# Tensor判定是否为finite/inf/nan
torch.isfinite(tensor) / torch.isinf(tensor) / torch.isnan(tensor)
返回一个标记元素是否为 有界/无界/nan 的mask 张量。返回张量

In [27]:
# 比较
a = torch.zeros(2,3)
b = torch.ones(2,3)
print(a)
print(b)
print(torch.eq(a,b))
print(torch.equal(a,b))
print(torch.gt(a,b))
print(torch.ge(a,b))
print(torch.lt(a,b))
print(torch.le(a,b))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])


In [28]:
# 排序
a = torch.Tensor([[3,1,7,5,9],
                  [6,4,8,2,10]])
print(a.shape)
print(torch.sort(a,dim=0,descending=False)) # 从小到大 descending=reverse

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[ 3.,  1.,  7.,  2.,  9.],
        [ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1]]))


In [29]:
# topk/kthvalue
print(torch.topk(a,k=2,dim=1))
print(torch.topk(a,k=1,dim=0))

torch.return_types.topk(
values=tensor([[ 9.,  7.],
        [10.,  8.]]),
indices=tensor([[4, 2],
        [4, 2]]))
torch.return_types.topk(
values=tensor([[ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[1, 1, 1, 0, 1]]))


In [30]:
a = torch.rand(2,3)
print(a)
print("a是否有界",torch.isfinite(a))
print("a是否有缺失值",torch.isnan(a))
print("a是否无界",torch.isinf(a))
print("a/0是否有界",torch.isfinite(a/0))
print("a/0是否有缺失值",torch.isnan(a/0))
print("a/0是否无界",torch.isinf(a/0))

tensor([[0.7575, 0.6897, 0.8943],
        [0.4047, 0.7027, 0.8164]])
a是否有界 tensor([[True, True, True],
        [True, True, True]])
a是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a是否无界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a/0是否无界 tensor([[True, True, True],
        [True, True, True]])


# Tensor的三角函数
 torch.abs(input, out=None)
 torch.acos(input, out=None)
 torch.asin(input, out=None)
 torch.atan(input, out=None)
 torch.atan2(input, inpu2, out=None)
 torch.cos(input, out=None)
 torch.cosh(input, out=None)
 torch.sin(input, out=None)
 torch.sinh(input, out=None)
 torch.tan(input, out=None)
 torch.tanh(input, out=None)

In [31]:
a = torch.zeros(2,3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# 其他的数学函数
torch.abs()
torch.sign()
torch.sigmoid() 激活函数

# Tensor中统计学相关的函数
torch.mean()    返回平均值
torch.sum()     返回总和
torch.prod()    计算所有元素的积
torch.max()     返回最大值
torch.min()     返回最小值
torch.argmax()  返回最大值排序的索引值
torch.argmin()  返回最小值排序的索引值
torch.std()     返回标准差
torch.var()     返回方差
torch.median()  返回中间值
torch.mode()    返回众数值
torch.histc()   计算input的直方图
torch.bincount()返回每个值得频数。

In [32]:
a = torch.rand(2,2)
print("a:",a)
print("mean",torch.mean(a,dim=1))
print("sum",torch.sum(a,dim=0))
print("prod",torch.prod(a))
# 通过指定某个维度来求和进行降维
print("argmax",torch.argmax(a,dim=0))
print("argmin",torch.argmin(a,dim=0))
print("std",torch.std(a,dim=1))
print("var",torch.var(a,dim=1))
print("median",torch.median(a))
print("mode",torch.mode(a))

a: tensor([[0.4471, 0.9446],
        [0.1403, 0.7283]])
mean tensor([0.6958, 0.4343])
sum tensor([0.5874, 1.6729])
prod tensor(0.0432)
argmax tensor([0, 0])
argmin tensor([1, 1])
std tensor([0.3518, 0.4158])
var tensor([0.1237, 0.1729])
median tensor(0.4471)
mode torch.return_types.mode(
values=tensor([0.4471, 0.1403]),
indices=tensor([0, 0]))


In [33]:
# 直方图
a = torch.rand(2,2)*10
print(a)
print(torch.histc(a,6,0,0))
print("a：输入的张量，这里是 torch.rand(2,2)*10 生成的一个 2×2 的张量，值在 0 到 10 之间"+
        "6：直方图的区间数量（bin 的数量），将数据范围分成 6 个等宽的区间"+
        "第一个 0：直方图的最小边界值（min value）"+
        "第二个 0：直方图的最大边界值（max value）"+
        "当最小值和最大值都设为 0 时，PyTorch 会自动使用输入张量中的实际最小值和最大值作为范围。所以这里实际上是将张量 a 中的所有值按照 6 个区间的宽度进行统计，并返回每个区间的计数值。"+
        "输出结果 tensor([1., 0., 0., 0., 1., 2.]) 表示："+
        "第1个区间有 1 个值"+
        "第2-4个区间各有 0 个值"+
        "第5个区间有 1 个值"+
        "第6个区间有 2 个值")

tensor([[2.2523, 4.3084],
        [3.2148, 3.3229]])
tensor([1., 0., 1., 1., 0., 1.])
a：输入的张量，这里是 torch.rand(2,2)*10 生成的一个 2×2 的张量，值在 0 到 10 之间6：直方图的区间数量（bin 的数量），将数据范围分成 6 个等宽的区间第一个 0：直方图的最小边界值（min value）第二个 0：直方图的最大边界值（max value）当最小值和最大值都设为 0 时，PyTorch 会自动使用输入张量中的实际最小值和最大值作为范围。所以这里实际上是将张量 a 中的所有值按照 6 个区间的宽度进行统计，并返回每个区间的计数值。输出结果 tensor([1., 0., 0., 0., 1., 2.]) 表示：第1个区间有 1 个值第2-4个区间各有 0 个值第5个区间有 1 个值第6个区间有 2 个值


In [34]:
"""
torch.randint(0,20,[10]) 生成了一个长度为10的张量，其中的值在0到19之间随机选择；而 torch.bincount(a) 则统计了每个值在张量中出现的次数，返回一个计数数组，数组的索引对应原始张量中的值，数组的值对应该值出现的次数，只适用于一维张量。
"""
a = torch.randint(0,20,[10])
print(a)
print(torch.bincount(a))
# 可以用来统计某一类别样本的个数

tensor([18, 16,  5,  5, 15,  0,  2, 11,  5, 13])
tensor([1, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])


# 分布函数
torch.distributions

# 随机抽样
torch.manual_seed() 定义随机种子

# 范数运算
> 在泛函分析中,它定义在赋范线性空间中,并满足一定的条件,即非负性;齐次性;三角不等式。
> 常被用来度量某个向量空间(或矩阵)中的每个向量的长度或大小。
 0范数(当前向量中非零元素之和)/1范数(元素的绝对值和)/2范数(欧式距离)/p范数(元素绝对值p次方和之后开p次根号)/核范数(低秩矩阵，图像处理)
> torch.dist(input, other, p=2) 计算p范数
> torch.norm() 计算2范数

作用：定义loss，向量之间的距离
     参数的约束，0范数即非零元素的个数，1范数即元素绝对值的和……

In [35]:
# 计算两个向量的l1和l2和lp距离
a = torch.rand([1,2])
b = torch.rand([1,2])
print(a,b)
print(torch.dist(a,b,p=1))
print(torch.dist(a,b,p=2))
print(torch.dist(a,b,p=3))
"""
torch.dist(a,b,p=3)：计算3范数距离，即差值的立方和再开三次方
"""

tensor([[0.3815, 0.7798]]) tensor([[0.1530, 0.4924]])
tensor(0.5160)
tensor(0.3672)
tensor(0.3292)


'\ntorch.dist(a,b,p=3)：计算3范数距离，即差值的立方和再开三次方\n'

In [36]:
# 打印a的二范数 元素和平方再开根号
print(torch.norm(a))

tensor(0.8682)


In [37]:
# 打印a的一三范数
print(a)
print(torch.norm(a,p=1))
print(torch.norm(a,p=3))
# 打印a的非零元素的个数
print(torch.norm(a,p=0))

tensor([[0.3815, 0.7798]])
tensor(1.1613)
tensor(0.8092)
tensor(2.)


In [38]:
# 打印a的核范数
print(torch.norm(a,p='fro'))

tensor(0.8682)


# Tensor中的矩阵分解
常见的矩阵分解
LU分解:将矩阵A分解成L(下三角)矩阵和U(上三角)矩阵的乘积
QR分解:将原矩阵分解成一个正交矩阵Q和一个上三角矩阵R的乘积

EVD分解:特征值分解 <-- PCA算法：主成分分析，降维，输入的必须是方阵
SVD分解:奇异值分解 <-- LDA算法：不用是方阵

# Tensor的裁剪运算
对Tensor中的元素进行范围过滤，将数据范围约束在一个比较小的的范围内时，使模型进行参数学习时更加稳定，防止模型过拟合。
常用于梯度裁剪(gradient clipping),即在发生梯度离散或者梯度爆炸时对梯度的处理
a.clamp(2,10) 把张量a约束在2到10之间

In [41]:
a = torch.rand(2,2)*10
print(a)
a = a.clamp(3,6)
print(a)
"""
tensor([[4.7214, 6.0000],
        [6.0000, 6.0000]])
"""

tensor([[4.7214, 9.9767],
        [8.0981, 7.0961]])
tensor([[4.7214, 6.0000],
        [6.0000, 6.0000]])


# Tensor的索引与数据筛选，聚合
torch.where(condition, x, y): 按照条件从x和y的tenser中选出满足条件condition的元素组成新的tensor
torch.gather(input, dim, index, out=None): 在指定维度上按照索引赋值输出tensor
torch.index_select(input, dim, index, out=None):按照指定索引输出tensor
torch.masked_select(input, mask, out=None): 按照mask输出tensor,输出为向量
torch.take(input, indices):将输入看成1D-tensor,按照索引得到输出tensor
torch.nonzero(input, out=None): 输出非0元素的坐标

In [43]:
a = torch.rand(4,4)
b = torch.rand(4,4)
print(a)
print(b)
out = torch.where(a>0.5,a,b)#当条件a>0.5为True时，选择a中的元素；否则选择b中的元素
print(out)

tensor([[0.7938, 0.0144, 0.4240, 0.0204],
        [0.2165, 0.2502, 0.6319, 0.9725],
        [0.6319, 0.8624, 0.1243, 0.7766],
        [0.9979, 0.5842, 0.9624, 0.6460]])
tensor([[0.8391, 0.9087, 0.2982, 0.3653],
        [0.5088, 0.1302, 0.7570, 0.0946],
        [0.0040, 0.7781, 0.6391, 0.1065],
        [0.7985, 0.4725, 0.3349, 0.5624]])
tensor([[0.7938, 0.9087, 0.2982, 0.3653],
        [0.5088, 0.1302, 0.6319, 0.9725],
        [0.6319, 0.8624, 0.6391, 0.7766],
        [0.9979, 0.5842, 0.9624, 0.6460]])


In [45]:
a = torch.rand(4,4)
print(a)
out = torch.index_select(a,dim=0,index = torch.tensor([3,0,2]))
print(out)
"""
torch.index_select() 是PyTorch中用于根据指定索引选择张量元素的函数
a 是输入的4x4张量
dim=0 表示在第0维度（行）上进行选择
index = torch.tensor([3,0,2]) 指定了要选择的行索引，按顺序选择第3行、第0行、第2行
结果 out 将是一个包含这些选定行的新张量
"""

tensor([[0.7109, 0.4763, 0.6644, 0.1914],
        [0.5031, 0.3292, 0.1502, 0.7041],
        [0.2840, 0.4552, 0.5208, 0.1540],
        [0.0703, 0.3557, 0.3209, 0.2509]])
tensor([[0.0703, 0.3557, 0.3209, 0.2509],
        [0.7109, 0.4763, 0.6644, 0.1914],
        [0.2840, 0.4552, 0.5208, 0.1540]])


''

In [46]:
a = torch.linspace(1,16,16).view(4,4)
#torch.linspace(1,16,16)：在1到16之间均匀地生成16个数值，生成的张量为 [1., 2., 3., ..., 16.].view(4,4)：将这16个数值重新塑形为4行4列的二维张量

print("a",a)
out = torch.gather(a,dim = 0,index = torch.tensor([[0,1,1,1],
                                                   [0,1,2,2]]))
print(out)
"""
具体解释：
a 是一个 4×4 的张量，内容为：
[[ 1.,  2.,  3.,  4.],
 [ 5.,  6.,  7.,  8.],
 [ 9., 10., 11., 12.],
 [13., 14., 15., 16.]]
dim = 0 表示在第0维度（行方向）上进行索引操作
index = torch.tensor([[0,1,1,1], [0,1,2,2]]) 是一个 2×4 的索引张量,[]里的数表示第几行
操作过程：
输出张量的形状与索引张量相同（2×4）
对于 index[0] = [0,1,1,1]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第1行取第2列元素(a[1,2]=7)，从第1行取第3列元素(a[1,3]=8)
对于 index[1] = [0,1,2,2]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第2行取第2列元素(a[2,2]=11)，从第2行取第3列元素(a[2,3]=12)
"""

a tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.]])


In [48]:
a = torch.linspace(1,16,16).view(4,4)
print("a",a)
mask = torch.gt(a,8)
print("mask",mask)
# 按照mask输出tensor,输出为向量
out = torch.masked_select(a,mask)
print("out",out)

a tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
mask tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
out tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [49]:
a = torch.linspace(1,16,16).view(4,4)
b = torch.take(a,index = torch.tensor([0,1,2,3,15,14]))
# 按照索引得到输出tensor
print(b)

tensor([ 1.,  2.,  3.,  4., 16., 15.])


In [50]:
a = torch.tensor([[1,0,0,2],[2,0,3,0]])
out = torch.nonzero(a)
# 输出非0元素的坐标
print(out)
# 稀疏矩阵表示

tensor([[0, 0],
        [0, 3],
        [1, 0],
        [1, 2]])
