# tensor 的定义

In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


In [3]:
a = torch.Tensor(2,3)
print(a)
print(a.type())

tensor([[-4.0883e+31,  2.0137e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.FloatTensor


In [4]:
a = torch.ones(2,2)
print(a)
print(a.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [5]:
a = torch.eye(2,2)
print(a)
print(a.type())

tensor([[1., 0.],
        [0., 1.]])
torch.FloatTensor


In [6]:
a = torch.zeros(2,2)
print(a)
print(a.type())

tensor([[0., 0.],
        [0., 0.]])
torch.FloatTensor


In [7]:
b = torch.Tensor(2,3)
a = torch.zeros_like(b)
print(a)
print(a.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [8]:
a = torch.ones_like(b)
print(a)
print(a.type())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [9]:
a = torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.4675, 0.6428, 0.0069],
        [0.8567, 0.5592, 0.3503]])
torch.FloatTensor


In [10]:
# 正态分布型
a = torch.normal(mean=0.0,std=torch.rand(5))
print(a)
print(a.type())

tensor([-1.5342, -0.0421,  0.1175,  1.3367,  0.9722])
torch.FloatTensor


In [11]:
a=torch.rand(5)
print(a)
print(a.type())

tensor([0.1400, 0.6269, 0.3599, 0.4774, 0.4055])
torch.FloatTensor


In [12]:
a=torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.3679, 0.7189, 0.7516],
        [0.7870, 0.6839, 0.4429]])
torch.FloatTensor


In [13]:
# 均匀分布
a = torch.Tensor(2,2).uniform_(-1,1)
print(a)
print(a.type())

tensor([[-0.6404, -0.9391],
        [-0.8778,  0.3760]])
torch.FloatTensor


In [14]:
# 序列生成
# 从0到10，以步长 3 递增，直到小于 11 的数字序列
a = torch.arange(0,11,3)
print(a)
print(a.type())

tensor([0, 3, 6, 9])
torch.LongTensor


In [15]:
# 2到10之间取等间隔的4个数
a = torch.linspace(2,10,4)
print(a)
print(a.type())

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
torch.FloatTensor


In [16]:
# 对样本进行随机打乱
a = torch.randperm(5)
b = torch.randperm(10)
print("a:",a)
print("b:",b)
print("a.type():",a.type())
print("b.type():",b.type())

a: tensor([0, 1, 4, 2, 3])
b: tensor([9, 5, 4, 8, 0, 3, 1, 2, 6, 7])
a.type(): torch.LongTensor
b.type(): torch.LongTensor


# tensor 属性
每一个Tensor都有数据类型（torch.dtype）和设备（torch.device）、内存布局（torch.layout)这三个属性。设备：在CPU还是在个GPU（cuda:0,1,2...)内存布局：是稠密（在内存中表示的是一块连续的存储空间）还是稀疏（在内存中表示的不是一块连续的存储空间，而是由多个不连续的存储空间组成的）

In [17]:
# 创建一个稠密张量并指定数据类型、设备和内存布局
a = torch.tensor([1,2,3],dtype=torch.float32,device=torch.device('cpu'))
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


## 创建一个稀疏张量
坐标值（indices）和对应的值（values）

In [18]:
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor


In [19]:
# 转成稠密张量打印
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())
y = torch.sparse_coo_tensor(indices,values,[3,4]).to_dense()
print(y)
print(y.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor
tensor([[0, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 0]])
torch.LongTensor


# tensor 算术运算

In [20]:
# add or sub
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a+b:",a+b)
print("a.add(b):",a.add(b))
print("torch.add(a,b):",torch.add(a,b))
print("a.add_(b):",a.add_(b))
print("a:",a)

a: tensor([[0.3343, 0.9782, 0.1746],
        [0.0887, 0.0051, 0.7631]])
b: tensor([[0.1595, 0.1649, 0.7659],
        [0.2174, 0.8249, 0.7136]])
a+b: tensor([[0.4938, 1.1431, 0.9405],
        [0.3061, 0.8300, 1.4767]])
a.add(b): tensor([[0.4938, 1.1431, 0.9405],
        [0.3061, 0.8300, 1.4767]])
torch.add(a,b): tensor([[0.4938, 1.1431, 0.9405],
        [0.3061, 0.8300, 1.4767]])
a.add_(b): tensor([[0.4938, 1.1431, 0.9405],
        [0.3061, 0.8300, 1.4767]])
a: tensor([[0.4938, 1.1431, 0.9405],
        [0.3061, 0.8300, 1.4767]])


In [21]:
# mul 乘（形状要相同）
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a*b:",a*b)
print("a.mul(b):",a.mul(b))
print("torch.mul(a,b):",torch.mul(a,b))
print("a.mul_(b):",a.mul_(b))
print("a:",a)

a: tensor([[0.7207, 0.8611, 0.2668],
        [0.9904, 0.5107, 0.5963]])
b: tensor([[0.5740, 0.5041, 0.8856],
        [0.7753, 0.4751, 0.0689]])
a*b: tensor([[0.4137, 0.4340, 0.2363],
        [0.7678, 0.2426, 0.0411]])
a.mul(b): tensor([[0.4137, 0.4340, 0.2363],
        [0.7678, 0.2426, 0.0411]])
torch.mul(a,b): tensor([[0.4137, 0.4340, 0.2363],
        [0.7678, 0.2426, 0.0411]])
a.mul_(b): tensor([[0.4137, 0.4340, 0.2363],
        [0.7678, 0.2426, 0.0411]])
a: tensor([[0.4137, 0.4340, 0.2363],
        [0.7678, 0.2426, 0.0411]])


In [22]:
# pow
a = torch.Tensor([1,2])
print("a**3:",a**3)
print("a.pow(3):",a.pow(3))
print("torch.pow(a,3):",torch.pow(a,3))
print("a.pow_(3):",a.pow_(3))

a**3: tensor([1., 8.])
a.pow(3): tensor([1., 8.])
torch.pow(a,3): tensor([1., 8.])
a.pow_(3): tensor([1., 8.])


In [23]:
# exp log sqrt
a = torch.tensor([1,2],dtype=torch.float32)
print("a.exp():",a.exp())
print("a.exp_():",a.exp_())
print("torch.exp(a):",torch.exp(a))
print("torch.exp_(a):",torch.exp_(a))

a.exp(): tensor([2.7183, 7.3891])
a.exp_(): tensor([2.7183, 7.3891])
torch.exp(a): tensor([  15.1543, 1618.1781])
torch.exp_(a): tensor([  15.1543, 1618.1781])


# tensor 矩阵运算

In [24]:
# matmul
a = torch.rand(2,3)
b = torch.rand(3,2)
print("a@b:",a@b)
print("a.matmul(b):",a.matmul(b))
print("torch.matmul(a,b):",torch.matmul(a,b))
print("a.matmul(b):",a.mm(b))
print("torch.matmul(a,b):",torch.mm(a,b))

a@b: tensor([[0.1234, 0.8495],
        [0.3027, 0.9183]])
a.matmul(b): tensor([[0.1234, 0.8495],
        [0.3027, 0.9183]])
torch.matmul(a,b): tensor([[0.1234, 0.8495],
        [0.3027, 0.9183]])
a.matmul(b): tensor([[0.1234, 0.8495],
        [0.3027, 0.9183]])
torch.matmul(a,b): tensor([[0.1234, 0.8495],
        [0.3027, 0.9183]])


# 高维tensor

In [25]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(a.matmul(b).shape)
# torch.Size([1, 2, 3, 3])

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
torch.Size([1, 2, 3, 3])


# in-place 操作
形如 x = x + y 不产生新的变量，还有上面的add_ sub_ mul_ pow_等等

# 广播机制
需要满足的两个条件：
1. 每个张量至少有一个维度
2. 两个张量的维度从最右边开始逐个比较，最右侧维度需要相等，前面维度用1补齐，最终维度：两个张量每一维二者取最大
第13个视频 6:30秒

# Tensor的取整/取余运算
.floor() 向下取整数
.ceil() 向上取整数
round() 四舍五入 >=0.5向上取整,<0.5向下取整
.trunc() 裁剪,只取整数部分
.frac() 只取小数部分
% 取余

In [27]:
a = torch.rand(2,2)
a = a * 10 #将rand生成的0-1之间的数转为1-10之间的数
print(a)
print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a%2)

tensor([[3.4042, 5.7678],
        [6.0185, 4.0415]])
tensor([[3., 5.],
        [6., 4.]])
tensor([[4., 6.],
        [7., 5.]])
tensor([[3., 6.],
        [6., 4.]])
tensor([[3., 5.],
        [6., 4.]])
tensor([[0.4042, 0.7678],
        [0.0185, 0.0415]])
tensor([[1.4042, 1.7678],
        [0.0185, 0.0415]])


# Tensor的比较运算
torch.eq(input, other, out=None) # 按每个成员进行等式操作,相同返回True或者false，类型是tensor
torch.equal(tensor1, tensor2)    # 如果tensor1和tensor2有相同的 size和elements,则为true
torch.ge(input, other, out=None) # input> = other
torch.gt(input, other, out=None) # input>other
torch.le(input, other, out=None) # input= < other
torch.It(input, other, out=None) # input<other
torch.ne(input, other, out=None) # input != other 不等于
# Tensor的取前k大/前k小/第k小的数值及其索引
torch.sort(input, dim=None, descending=False, out=None) #xf 目标input进行排序
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None)#沿着指定维度返回==最大==k个数值及其索引值
torch.kthvalue(input, k, dim=None, out=None)  #沿着指定维度返回第k个==最小==值及其索引值
# Tensor判定是否为finite/inf/nan
torch.isfinite(tensor) / torch.isinf(tensor) / torch.isnan(tensor)
返回一个标记元素是否为 有界/无界/nan 的mask 张量。返回张量

In [30]:
# 比较
a = torch.zeros(2,3)
b = torch.ones(2,3)
print(a)
print(b)
print(torch.eq(a,b))
print(torch.equal(a,b))
print(torch.gt(a,b))
print(torch.ge(a,b))
print(torch.lt(a,b))
print(torch.le(a,b))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])


In [33]:
# 排序
a = torch.Tensor([[3,1,7,5,9],
                  [6,4,8,2,10]])
print(a.shape)
print(torch.sort(a,dim=0,descending=False)) # 从小到大 descending=reverse

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[ 3.,  1.,  7.,  2.,  9.],
        [ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1]]))


In [41]:
# topk/kthvalue
print(torch.topk(a,k=2,dim=1))
print(torch.topk(a,k=1,dim=0))

torch.return_types.topk(
values=tensor([[ 9.,  7.],
        [10.,  8.]]),
indices=tensor([[4, 2],
        [4, 2]]))
torch.return_types.topk(
values=tensor([[ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[1, 1, 1, 0, 1]]))


In [42]:
a = torch.rand(2,3)
print(a)
print("a是否有界",torch.isfinite(a))
print("a是否有缺失值",torch.isnan(a))
print("a是否无界",torch.isinf(a))
print("a/0是否有界",torch.isfinite(a/0))
print("a/0是否有缺失值",torch.isnan(a/0))
print("a/0是否无界",torch.isinf(a/0))

tensor([[0.2492, 0.4496, 0.5641],
        [0.4510, 0.0548, 0.5964]])
a是否有界 tensor([[True, True, True],
        [True, True, True]])
a是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a是否无界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a/0是否无界 tensor([[True, True, True],
        [True, True, True]])


# Tensor的三角函数
 torch.abs(input, out=None)
 torch.acos(input, out=None)
 torch.asin(input, out=None)
 torch.atan(input, out=None)
 torch.atan2(input, inpu2, out=None)
 torch.cos(input, out=None)
 torch.cosh(input, out=None)
 torch.sin(input, out=None)
 torch.sinh(input, out=None)
 torch.tan(input, out=None)
 torch.tanh(input, out=None)

In [44]:
a = torch.zeros(2,3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
