# tensor 的定义

In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


In [3]:
a = torch.Tensor(2,3)
print(a)
print(a.type())

tensor([[-5.9732e+28,  1.2486e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.FloatTensor


In [4]:
a = torch.ones(2,2)
print(a)
print(a.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [5]:
a = torch.eye(2,2)
print(a)
print(a.type())

tensor([[1., 0.],
        [0., 1.]])
torch.FloatTensor


In [6]:
a = torch.zeros(2,2)
print(a)
print(a.type())

tensor([[0., 0.],
        [0., 0.]])
torch.FloatTensor


In [7]:
b = torch.Tensor(2,3)
a = torch.zeros_like(b)
print(a)
print(a.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [8]:
a = torch.ones_like(b)
print(a)
print(a.type())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [9]:
a = torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.3584, 0.3572, 0.8069],
        [0.0358, 0.2029, 0.5583]])
torch.FloatTensor


In [10]:
# 正态分布型
a = torch.normal(mean=0.0,std=torch.rand(5))
print(a)
print(a.type())

tensor([ 0.2557, -0.0014, -0.2108,  0.0723,  0.0370])
torch.FloatTensor


In [11]:
a=torch.rand(5)
print(a)
print(a.type())

tensor([0.9768, 0.4216, 0.1024, 0.3096, 0.6825])
torch.FloatTensor


In [12]:
a=torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.3816, 0.7896, 0.8639],
        [0.3528, 0.2085, 0.7353]])
torch.FloatTensor


In [13]:
# 均匀分布
a = torch.Tensor(2,2).uniform_(-1,1)
"""
torch.Tensor(2,2) - 创建一个 2×2 维的空张量（未初始化状态）
.uniform_(-1,1) - 使用就地（in-place）方法，将张量中的元素填充为在区间 [-1, 1] 内均匀分布的随机数
"""
print(a)
print(a.type())

tensor([[-0.3099, -0.8237],
        [-0.7894, -0.4181]])
torch.FloatTensor


In [14]:
# 序列生成
# 从0到10，以步长 3 递增，直到小于 11 的数字序列
a = torch.arange(0,11,3)
print(a)
print(a.type())

tensor([0, 3, 6, 9])
torch.LongTensor


In [15]:
# 2到10之间取等间隔的4个数
a = torch.linspace(2,10,4)
print(a)
print(a.type())

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
torch.FloatTensor


In [16]:
# 对样本进行随机打乱
a = torch.randperm(5)
b = torch.randperm(10)
print("a:",a)
print("b:",b)
print("a.type():",a.type())
print("b.type():",b.type())

a: tensor([1, 4, 2, 3, 0])
b: tensor([3, 2, 0, 4, 5, 8, 7, 9, 1, 6])
a.type(): torch.LongTensor
b.type(): torch.LongTensor


# tensor 属性
每一个Tensor都有数据类型（torch.dtype）和设备（torch.device）、内存布局（torch.layout)这三个属性。设备：在CPU还是在个GPU（cuda:0,1,2...)内存布局：是稠密（在内存中表示的是一块连续的存储空间）还是稀疏（在内存中表示的不是一块连续的存储空间，而是由多个不连续的存储空间组成的）

In [17]:
# 创建一个稠密张量并指定数据类型、设备和内存布局
a = torch.tensor([1,2,3],dtype=torch.float32,device=torch.device('cpu'))
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


## 创建一个稀疏张量
坐标值（indices）和对应的值（values）

In [18]:
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor


In [19]:
# 转成稠密张量打印
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())
y = torch.sparse_coo_tensor(indices,values,[3,4]).to_dense()
print(y)
print(y.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor
tensor([[0, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 0]])
torch.LongTensor


# tensor 算术运算

In [20]:
# add or sub
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a+b:",a+b)
print("a.add(b):",a.add(b))
print("torch.add(a,b):",torch.add(a,b))
print("a.add_(b):",a.add_(b))
print("a:",a)

a: tensor([[0.7597, 0.3064, 0.5570],
        [0.2572, 0.6312, 0.8570]])
b: tensor([[0.3302, 0.2868, 0.1924],
        [0.9036, 0.9189, 0.7837]])
a+b: tensor([[1.0899, 0.5932, 0.7494],
        [1.1608, 1.5501, 1.6407]])
a.add(b): tensor([[1.0899, 0.5932, 0.7494],
        [1.1608, 1.5501, 1.6407]])
torch.add(a,b): tensor([[1.0899, 0.5932, 0.7494],
        [1.1608, 1.5501, 1.6407]])
a.add_(b): tensor([[1.0899, 0.5932, 0.7494],
        [1.1608, 1.5501, 1.6407]])
a: tensor([[1.0899, 0.5932, 0.7494],
        [1.1608, 1.5501, 1.6407]])


In [21]:
# mul 乘（形状要相同）
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a*b:",a*b)
print("a.mul(b):",a.mul(b))
print("torch.mul(a,b):",torch.mul(a,b))
print("a.mul_(b):",a.mul_(b))
print("a:",a)

a: tensor([[0.3253, 0.0737, 0.6018],
        [0.1105, 0.7857, 0.1337]])
b: tensor([[0.9113, 0.1433, 0.3696],
        [0.6317, 0.6130, 0.0071]])
a*b: tensor([[0.2964, 0.0106, 0.2224],
        [0.0698, 0.4817, 0.0010]])
a.mul(b): tensor([[0.2964, 0.0106, 0.2224],
        [0.0698, 0.4817, 0.0010]])
torch.mul(a,b): tensor([[0.2964, 0.0106, 0.2224],
        [0.0698, 0.4817, 0.0010]])
a.mul_(b): tensor([[0.2964, 0.0106, 0.2224],
        [0.0698, 0.4817, 0.0010]])
a: tensor([[0.2964, 0.0106, 0.2224],
        [0.0698, 0.4817, 0.0010]])


In [22]:
# pow
a = torch.Tensor([1,2])
print("a**3:",a**3)
print("a.pow(3):",a.pow(3))
print("torch.pow(a,3):",torch.pow(a,3))
print("a.pow_(3):",a.pow_(3))

a**3: tensor([1., 8.])
a.pow(3): tensor([1., 8.])
torch.pow(a,3): tensor([1., 8.])
a.pow_(3): tensor([1., 8.])


In [23]:
# exp log sqrt
a = torch.tensor([1,2],dtype=torch.float32)
print("a.exp():",a.exp())
print("a.exp_():",a.exp_())
print("torch.exp(a):",torch.exp(a))
print("torch.exp_(a):",torch.exp_(a))

a.exp(): tensor([2.7183, 7.3891])
a.exp_(): tensor([2.7183, 7.3891])
torch.exp(a): tensor([  15.1543, 1618.1781])
torch.exp_(a): tensor([  15.1543, 1618.1781])


# tensor 矩阵运算

In [24]:
# matmul
a = torch.rand(2,3)
b = torch.rand(3,2)
print("a@b:",a@b)
print("a.matmul(b):",a.matmul(b))
print("torch.matmul(a,b):",torch.matmul(a,b))
print("a.matmul(b):",a.mm(b))
print("torch.matmul(a,b):",torch.mm(a,b))

a@b: tensor([[0.7383, 0.2717],
        [1.0976, 0.7614]])
a.matmul(b): tensor([[0.7383, 0.2717],
        [1.0976, 0.7614]])
torch.matmul(a,b): tensor([[0.7383, 0.2717],
        [1.0976, 0.7614]])
a.matmul(b): tensor([[0.7383, 0.2717],
        [1.0976, 0.7614]])
torch.matmul(a,b): tensor([[0.7383, 0.2717],
        [1.0976, 0.7614]])


# 高维tensor

In [25]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(a.matmul(b).shape)
# torch.Size([1, 2, 3, 3])

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
torch.Size([1, 2, 3, 3])


# in-place 操作
形如 x = x + y 不产生新的变量，还有上面的add_ sub_ mul_ pow_等等

# 广播机制
需要满足的两个条件：
1. 每个张量至少有一个维度
2. 两个张量的维度从最右边开始逐个比较，最右侧维度需要相等，前面维度用1补齐，最终维度：两个张量每一维二者取最大
第13个视频 6:30秒

# Tensor的取整/取余运算
.floor() 向下取整数
.ceil() 向上取整数
round() 四舍五入 >=0.5向上取整,<0.5向下取整
.trunc() 裁剪,只取整数部分
.frac() 只取小数部分
% 取余

In [26]:
a = torch.rand(2,2)
a = a * 10 #将rand生成的0-1之间的数转为1-10之间的数
print(a)
print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a%2)

tensor([[3.1277, 2.5427],
        [9.3646, 0.7925]])
tensor([[3., 2.],
        [9., 0.]])
tensor([[ 4.,  3.],
        [10.,  1.]])
tensor([[3., 3.],
        [9., 1.]])
tensor([[3., 2.],
        [9., 0.]])
tensor([[0.1277, 0.5427],
        [0.3646, 0.7925]])
tensor([[1.1277, 0.5427],
        [1.3646, 0.7925]])


# Tensor的比较运算
torch.eq(input, other, out=None) # 按每个成员进行等式操作,相同返回True或者false，类型是tensor
torch.equal(tensor1, tensor2)    # 如果tensor1和tensor2有相同的 size和elements,则为true
torch.ge(input, other, out=None) # input> = other
torch.gt(input, other, out=None) # input>other
torch.le(input, other, out=None) # input= < other
torch.It(input, other, out=None) # input<other
torch.ne(input, other, out=None) # input != other 不等于
# Tensor的取前k大/前k小/第k小的数值及其索引
torch.sort(input, dim=None, descending=False, out=None) #xf 目标input进行排序
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None)#沿着指定维度返回==最大==k个数值及其索引值
torch.kthvalue(input, k, dim=None, out=None)  #沿着指定维度返回第k个==最小==值及其索引值
# Tensor判定是否为finite/inf/nan
torch.isfinite(tensor) / torch.isinf(tensor) / torch.isnan(tensor)
返回一个标记元素是否为 有界/无界/nan 的mask 张量。返回张量

In [27]:
# 比较
a = torch.zeros(2,3)
b = torch.ones(2,3)
print(a)
print(b)
print(torch.eq(a,b))
print(torch.equal(a,b))
print(torch.gt(a,b))
print(torch.ge(a,b))
print(torch.lt(a,b))
print(torch.le(a,b))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])


In [28]:
# 排序
a = torch.Tensor([[3,1,7,5,9],
                  [6,4,8,2,10]])
print(a.shape)
print(torch.sort(a,dim=0,descending=False)) # 从小到大 descending=reverse
"""
当 dim=0 时，会在每一列内进行排序，将每列的元素按升序排列
这意味着张量中每一列的元素会被独立排序，较小的值会排到上面的行，较大的值会排到下面的行
"""

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[ 3.,  1.,  7.,  2.,  9.],
        [ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1]]))


'\n当 dim=0 时，会在每一列内进行排序，将每列的元素按升序排列\n这意味着张量中每一列的元素会被独立排序，较小的值会排到上面的行，较大的值会排到下面的行\n'

In [29]:
# topk/kthvalue
print(a)
print(torch.topk(a,k=2,dim=1))
print("-------------")
print(torch.topk(a,k=1,dim=0))

tensor([[ 3.,  1.,  7.,  5.,  9.],
        [ 6.,  4.,  8.,  2., 10.]])
torch.return_types.topk(
values=tensor([[ 9.,  7.],
        [10.,  8.]]),
indices=tensor([[4, 2],
        [4, 2]]))
-------------
torch.return_types.topk(
values=tensor([[ 6.,  4.,  8.,  5., 10.]]),
indices=tensor([[1, 1, 1, 0, 1]]))


In [30]:
a = torch.rand(2,3)
print(a)
print("a是否有界",torch.isfinite(a))
print("a是否有缺失值",torch.isnan(a))
print("a是否无界",torch.isinf(a))
print("a/0是否有界",torch.isfinite(a/0))
print("a/0是否有缺失值",torch.isnan(a/0))
print("a/0是否无界",torch.isinf(a/0))

tensor([[0.2543, 0.9017, 0.2527],
        [0.8319, 0.8726, 0.9610]])
a是否有界 tensor([[True, True, True],
        [True, True, True]])
a是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a是否无界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有界 tensor([[False, False, False],
        [False, False, False]])
a/0是否有缺失值 tensor([[False, False, False],
        [False, False, False]])
a/0是否无界 tensor([[True, True, True],
        [True, True, True]])


# Tensor的三角函数
 torch.abs(input, out=None)
 torch.acos(input, out=None)
 torch.asin(input, out=None)
 torch.atan(input, out=None)
 torch.atan2(input, inpu2, out=None)
 torch.cos(input, out=None)
 torch.cosh(input, out=None)
 torch.sin(input, out=None)
 torch.sinh(input, out=None)
 torch.tan(input, out=None)
 torch.tanh(input, out=None)

In [31]:
a = torch.zeros(2,3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# 其他的数学函数
torch.abs()
torch.sign()
torch.sigmoid() 激活函数

# Tensor中统计学相关的函数
torch.mean()    返回平均值
torch.sum()     返回总和
torch.prod()    计算所有元素的积
torch.max()     返回最大值
torch.min()     返回最小值
torch.argmax()  返回最大值排序的索引值
torch.argmin()  返回最小值排序的索引值
torch.std()     返回标准差
torch.var()     返回方差
torch.median()  返回中间值
torch.mode()    返回众数值
torch.histc()   计算input的直方图
torch.bincount()返回每个值得频数。

In [32]:
a = torch.rand(2,2)
print("a:",a)
print("mean",torch.mean(a,dim=1))
print("sum",torch.sum(a,dim=0))
print("prod",torch.prod(a))#计算所有元素的积
# 通过指定某个维度来求和进行降维
print("argmax",torch.argmax(a,dim=0))#返回最小值排序的索引值
print("argmin",torch.argmin(a,dim=0))
print("std",torch.std(a,dim=1))
print("var",torch.var(a,dim=1))
print("median",torch.median(a))
print("mode",torch.mode(a))

a: tensor([[0.6389, 0.8470],
        [0.4763, 0.3028]])
mean tensor([0.7430, 0.3896])
sum tensor([1.1152, 1.1498])
prod tensor(0.0781)
argmax tensor([0, 0])
argmin tensor([1, 1])
std tensor([0.1472, 0.1227])
var tensor([0.0217, 0.0151])
median tensor(0.4763)
mode torch.return_types.mode(
values=tensor([0.6389, 0.3028]),
indices=tensor([0, 1]))


In [33]:
# 直方图
a = torch.rand(2,2)*10
print(a)
print(torch.histc(a,6,0,0))
print("a：输入的张量，这里是 torch.rand(2,2)*10 生成的一个 2×2 的张量，值在 0 到 10 之间"+
        "6：直方图的区间数量（bin 的数量），将数据范围分成 6 个等宽的区间"+
        "第一个 0：直方图的最小边界值（min value）"+
        "第二个 0：直方图的最大边界值（max value）"+
        "当最小值和最大值都设为 0 时，PyTorch 会自动使用输入张量中的实际最小值和最大值作为范围。所以这里实际上是将张量 a 中的所有值按照 6 个区间的宽度进行统计，并返回每个区间的计数值。"+
        "输出结果 tensor([1., 0., 0., 0., 1., 2.]) 表示："+
        "第1个区间有 1 个值"+
        "第2-4个区间各有 0 个值"+
        "第5个区间有 1 个值"+
        "第6个区间有 2 个值")

tensor([[7.0804, 8.6614],
        [9.5527, 2.1999]])
tensor([1., 0., 0., 1., 0., 2.])
a：输入的张量，这里是 torch.rand(2,2)*10 生成的一个 2×2 的张量，值在 0 到 10 之间6：直方图的区间数量（bin 的数量），将数据范围分成 6 个等宽的区间第一个 0：直方图的最小边界值（min value）第二个 0：直方图的最大边界值（max value）当最小值和最大值都设为 0 时，PyTorch 会自动使用输入张量中的实际最小值和最大值作为范围。所以这里实际上是将张量 a 中的所有值按照 6 个区间的宽度进行统计，并返回每个区间的计数值。输出结果 tensor([1., 0., 0., 0., 1., 2.]) 表示：第1个区间有 1 个值第2-4个区间各有 0 个值第5个区间有 1 个值第6个区间有 2 个值


In [34]:
"""
torch.randint(0,20,[10]) 生成了一个长度为10的张量，其中的值在0到19之间随机选择；而 torch.bincount(a) 则统计了每个值在张量中出现的次数，返回一个计数数组，数组的索引对应原始张量中的值，数组的值对应该值出现的次数，只适用于一维张量。
"""
a = torch.randint(0,20,[10])
print(a)
print(torch.bincount(a))
# 可以用来统计某一类别样本的个数

tensor([ 4, 14, 12,  2, 10, 12, 13, 16, 10,  4])
tensor([0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 1])


# 分布函数
torch.distributions

# 随机抽样
torch.manual_seed() 定义随机种子

# 范数运算
> 在泛函分析中,它定义在赋范线性空间中,并满足一定的条件,即非负性;齐次性;三角不等式。
> 常被用来度量某个向量空间(或矩阵)中的每个向量的长度或大小。
 0范数(当前向量中非零元素之和)/1范数(元素的绝对值和)/2范数(欧式距离)/p范数(元素绝对值p次方和之后开p次根号)/核范数(低秩矩阵，图像处理)
> torch.dist(input, other, p=2) 计算p范数
> torch.norm() 计算2范数

作用：定义loss，向量之间的距离
     参数的约束，0范数即非零元素的个数，1范数即元素绝对值的和……

In [35]:
# 计算两个向量的l1和l2和lp距离
a = torch.rand([1,2])
b = torch.rand([1,2])
print(a,b)
print(torch.dist(a,b,p=1))
print(torch.dist(a,b,p=2))
print(torch.dist(a,b,p=3))
"""
torch.dist(a,b,p=3)：计算3范数距离，即差值的立方和再开三次方
"""

tensor([[0.5161, 0.0341]]) tensor([[0.9345, 0.8215]])
tensor(1.2059)
tensor(0.8917)
tensor(0.8250)


'\ntorch.dist(a,b,p=3)：计算3范数距离，即差值的立方和再开三次方\n'

In [36]:
# 打印a的二范数 元素和平方再开根号
print(torch.norm(a))

tensor(0.5172)


In [37]:
# 打印a的一三范数
print(a)
print(torch.norm(a,p=1))
print(torch.norm(a,p=3))
'''
a = torch.tensor([[0.2754, 0.2001]])
计算每个元素的绝对值的3次方：
|0.2754|^3 = 0.2754^3 ≈ 0.0209
|0.2001|^3 = 0.2001^3 ≈ 0.0080
求和：0.0209 + 0.0080 = 0.0289
开3次方根：$0.0289^{1/3} ≈ 0.3069
'''
# 打印a的非零元素的个数
print(torch.norm(a,p=0))

tensor([[0.5161, 0.0341]])
tensor(0.5501)
tensor(0.5161)
tensor(2.)


In [38]:
# 打印a的核范数
print(torch.norm(a,p='fro'))
#核范数(低秩矩阵，图像处理)

tensor(0.5172)


# Tensor中的矩阵分解
常见的矩阵分解
LU分解:将矩阵A分解成L(下三角)矩阵和U(上三角)矩阵的乘积
QR分解:将原矩阵分解成一个正交矩阵Q和一个上三角矩阵R的乘积

EVD分解:特征值分解 <-- PCA算法：主成分分析，降维，输入的必须是方阵
SVD分解:奇异值分解 <-- LDA算法：不用是方阵

# Tensor的裁剪运算
对Tensor中的元素进行范围过滤，将数据范围约束在一个比较小的的范围内时，使模型进行参数学习时更加稳定，防止模型过拟合。
常用于梯度裁剪(gradient clipping),即在发生梯度离散或者梯度爆炸时对梯度的处理
a.clamp(2,10) 把张量a约束在2到10之间

In [39]:
a = torch.rand(2,2)*10
print(a)
a = a.clamp(3,6)
print(a)
"""
tensor([[4.7214, 6.0000],
        [6.0000, 6.0000]])
"""

tensor([[3.0349, 0.6038],
        [4.5114, 1.4473]])
tensor([[3.0349, 3.0000],
        [4.5114, 3.0000]])


'\ntensor([[4.7214, 6.0000],\n        [6.0000, 6.0000]])\n'

# Tensor的索引与数据筛选，聚合
torch.where(condition, x, y): 按照条件从x和y的tenser中选出满足条件condition的元素组成新的tensor
torch.gather(input, dim, index, out=None): 在指定维度上按照索引赋值输出tensor
torch.index_select(input, dim, index, out=None):按照指定索引输出tensor
torch.masked_select(input, mask, out=None): 按照mask输出tensor,输出为向量
torch.take(input, indices):将输入看成1D-tensor,按照索引得到输出tensor
torch.nonzero(input, out=None): 输出非0元素的坐标

In [40]:
a = torch.rand(4,4)
b = torch.rand(4,4)
print(a)
print(b)
out = torch.where(a>0.5,a,b)#当条件a>0.5为True时，选择a中的元素；否则选择b中的元素
print(out)

tensor([[0.8607, 0.8464, 0.2832, 0.3718],
        [0.7163, 0.7054, 0.7982, 0.9914],
        [0.9990, 0.5910, 0.2527, 0.2510],
        [0.9797, 0.2303, 0.8386, 0.5236]])
tensor([[0.3042, 0.9499, 0.5106, 0.9857],
        [0.1360, 0.4788, 0.7849, 0.3515],
        [0.1337, 0.4154, 0.1709, 0.6461],
        [0.4807, 0.8681, 0.7890, 0.3553]])
tensor([[0.8607, 0.8464, 0.5106, 0.9857],
        [0.7163, 0.7054, 0.7982, 0.9914],
        [0.9990, 0.5910, 0.1709, 0.6461],
        [0.9797, 0.8681, 0.8386, 0.5236]])


In [41]:
a = torch.rand(4,4)
print(a)
out = torch.index_select(a,dim=0,index = torch.tensor([3,0,2]))
print(out)
"""
torch.index_select() 是PyTorch中用于根据指定索引选择张量元素的函数
a 是输入的4x4张量
dim=0 表示在第0维度（行）上进行选择
index = torch.tensor([3,0,2]) 指定了要选择的行索引，按顺序选择第3行、第0行、第2行
结果 out 将是一个包含这些选定行的新张量
"""

tensor([[0.5647, 0.5746, 0.6948, 0.8880],
        [0.4187, 0.3274, 0.6382, 0.2517],
        [0.1884, 0.0986, 0.9397, 0.4093],
        [0.1676, 0.0059, 0.5789, 0.2256]])
tensor([[0.1676, 0.0059, 0.5789, 0.2256],
        [0.5647, 0.5746, 0.6948, 0.8880],
        [0.1884, 0.0986, 0.9397, 0.4093]])


'\ntorch.index_select() 是PyTorch中用于根据指定索引选择张量元素的函数\na 是输入的4x4张量\ndim=0 表示在第0维度（行）上进行选择\nindex = torch.tensor([3,0,2]) 指定了要选择的行索引，按顺序选择第3行、第0行、第2行\n结果 out 将是一个包含这些选定行的新张量\n'

In [42]:
a = torch.linspace(1,16,16).view(4,4)
#torch.linspace(1,16,16)：在1到16之间均匀地生成16个数值，生成的张量为 [1., 2., 3., ..., 16.].view(4,4)：将这16个数值重新塑形为4行4列的二维张量

print("a",a)
out = torch.gather(a,dim = 0,index = torch.tensor([[0,1,1,1],
                                                   [0,1,2,2]]))
print(out)
"""
具体解释：
a 是一个 4×4 的张量，内容为：
[[ 1.,  2.,  3.,  4.],
 [ 5.,  6.,  7.,  8.],
 [ 9., 10., 11., 12.],
 [13., 14., 15., 16.]]
dim = 0 表示在第0维度（行方向）上进行索引操作
index = torch.tensor([[0,1,1,1], [0,1,2,2]]) 是一个 2×4 的索引张量,[]里的数表示第几行
操作过程：
输出张量的形状与索引张量相同（2×4）
对于 index[0] = [0,1,1,1]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第1行取第2列元素(a[1,2]=7)，从第1行取第3列元素(a[1,3]=8)
对于 index[1] = [0,1,2,2]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第2行取第2列元素(a[2,2]=11)，从第2行取第3列元素(a[2,3]=12)
"""

a tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.]])


'\n具体解释：\na 是一个 4×4 的张量，内容为：\n[[ 1.,  2.,  3.,  4.],\n [ 5.,  6.,  7.,  8.],\n [ 9., 10., 11., 12.],\n [13., 14., 15., 16.]]\ndim = 0 表示在第0维度（行方向）上进行索引操作\nindex = torch.tensor([[0,1,1,1], [0,1,2,2]]) 是一个 2×4 的索引张量,[]里的数表示第几行\n操作过程：\n输出张量的形状与索引张量相同（2×4）\n对于 index[0] = [0,1,1,1]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第1行取第2列元素(a[1,2]=7)，从第1行取第3列元素(a[1,3]=8)\n对于 index[1] = [0,1,2,2]：从第0行取第0列元素(a[0,0]=1)，从第1行取第1列元素(a[1,1]=6)，从第2行取第2列元素(a[2,2]=11)，从第2行取第3列元素(a[2,3]=12)\n'

In [43]:
a = torch.linspace(1,16,16).view(4,4)
print("a",a)
mask = torch.gt(a,8)
print("mask",mask)
# 按照mask输出tensor,输出为向量
out = torch.masked_select(a,mask)
print("out",out)

a tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
mask tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
out tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [44]:
a = torch.linspace(1,16,16).view(4,4)
b = torch.take(a,index = torch.tensor([0,1,2,3,15,14]))
# 按照索引得到输出tensor
print(b)

tensor([ 1.,  2.,  3.,  4., 16., 15.])


In [45]:
a = torch.tensor([[1,0,0,2],[2,0,3,0]])
out = torch.nonzero(a)
# 输出非0元素的坐标
print(out)
# 稀疏矩阵表示

tensor([[0, 0],
        [0, 3],
        [1, 0],
        [1, 2]])


# Tensor的组合/拼接
重要的是torch.cat(seq, dim=0, out=None):按照已经存在的维度进行拼接
torch.stack(seq, dim=0, out=None): 按照新的维度进行拼接
torch.gather(input, dim, index, out=None): 在指定维度上按照索引赋值输出tensor

In [46]:
# 不改变维度数,拼接张示, 除了拼接的那个维度外,其它维度数必须保持一致.
a = torch.zeros((2,4))
b = torch.ones((2,4))
print("a",a)
print("b",b)
out1 = torch.cat((a,b),dim=0)
out2 = torch.cat((a,b),dim=1)
print("out1",out1)
print("out1.shape",out1.shape)
print("out2",out2)
print("out2.shape",out2.shape)


a tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
b tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
out1 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
out1.shape torch.Size([4, 4])
out2 tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])
out2.shape torch.Size([2, 8])


In [78]:
# 会改变维度数,拼接张示, 所有的维度都必须保持一致
a = torch.linspace(1,6,6).view(2,3)
b = torch.linspace(7,12,6).view(2,3)
print("a",a)
print("b",b)
out1 = torch.stack((a,b),dim=0)
out2 = torch.stack((a,b),dim=1)
out3 = torch.stack((a,b),dim=2)
print("out1",out1)
print("out1.shape",out1.shape)
print("out2",out2)
print("out2.shape",out2.shape)
print("out3",out3)
print("out3.shape",out3.shape)
"""
t1和t2都是二维张量
# 思路2: stack() 拼接张量,可以是新维度,但是无论新旧维度,所有维度都必须保持一致.
# t7 = torch.stack([t1, t2], dim=0) # (2, 3) + (2, 3) = (2, 2, 3)
# print(f't7: {t7}, shape: {t7. shape} ')
# t8 = torch.stack([t1, t2], dim=1) # (2, 3) + (2, 3) = (2, 2, 3)
# print(f't8: {t8}, shape: {t8. shape} ')
# t9 = torch.stack([t1, t2], dim=2) # (2, 3) + (2, 3) = (2, 3, 2)
# print(f't9: {t9}, shape: {[t9. shape}')
# 报错. t10 = torch.stack( tensors: [t1, t2], dim=3) # (2, 3) + (2, 3) = (2, 3, ?, 2)
# print(f't10: {t10}, shape: {t10. shape} ')
"""

a tensor([[1., 2., 3.],
        [4., 5., 6.]])
b tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
out1 tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
out1.shape torch.Size([2, 2, 3])
out2 tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
out2.shape torch.Size([2, 2, 3])
out3 tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
out3.shape torch.Size([2, 3, 2])


''

In [48]:

out2 = torch.stack((a,b),dim=0)
print("a=out2[0::]",out2[0,:,:])
print("b=out2[1::]",out2[1,:,:])
out2 = torch.stack((a,b),dim=1)
print("a=out2[:0:]",out2[:,0,:])
print("b=out2[:1:]",out2[:,1,:])
out2 = torch.stack((a,b),dim=2)
print("a=out2[::0]",out2[:,:,0])
print("b=out2[::1]",out2[:,:,1])

a=out2[0::] tensor([[1., 2., 3.],
        [4., 5., 6.]])
b=out2[1::] tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
a=out2[:0:] tensor([[1., 2., 3.],
        [4., 5., 6.]])
b=out2[:1:] tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
a=out2[::0] tensor([[1., 2., 3.],
        [4., 5., 6.]])
b=out2[::1] tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


# Tensor的切片
torch.chunk(tensor, chunks, dim=0): 按照某个维度平均分块(最 后一个可能小于平均值)
重要的是：torch.split(tensor, split_size_or_sections, dim=0): 按照某个维度 依照第二个参数给出的list或者int进行分割tensor

In [49]:
a = torch.rand((3,4))
print("a",a)
out = torch.chunk(a,2,dim=0)
print("out",out)
print("out[0]",out[0])
print("out[1]",out[1])

a tensor([[0.8893, 0.8725, 0.1453, 0.3532],
        [0.5011, 0.2986, 0.8984, 0.8542],
        [0.4077, 0.4916, 0.0445, 0.3401]])
out (tensor([[0.8893, 0.8725, 0.1453, 0.3532],
        [0.5011, 0.2986, 0.8984, 0.8542]]), tensor([[0.4077, 0.4916, 0.0445, 0.3401]]))
out[0] tensor([[0.8893, 0.8725, 0.1453, 0.3532],
        [0.5011, 0.2986, 0.8984, 0.8542]])
out[1] tensor([[0.4077, 0.4916, 0.0445, 0.3401]])


In [50]:
out = torch.chunk(a,2,dim=1)
print("out",out)
print("out[0]",out[0])
print("out[1]",out[1])

out (tensor([[0.8893, 0.8725],
        [0.5011, 0.2986],
        [0.4077, 0.4916]]), tensor([[0.1453, 0.3532],
        [0.8984, 0.8542],
        [0.0445, 0.3401]]))
out[0] tensor([[0.8893, 0.8725],
        [0.5011, 0.2986],
        [0.4077, 0.4916]])
out[1] tensor([[0.1453, 0.3532],
        [0.8984, 0.8542],
        [0.0445, 0.3401]])


In [51]:
b = torch.rand((10,4))
print("b",b)
out1 = torch.split(b,3,dim=0)
out2 = torch.split(b,3,dim=1)
out3 = torch.split(b,[1,4,5],dim=0)
out4 = torch.split(b,[1,1,2],dim=1)
print("out1")
for i in out1:
    print(i,i.shape)
print("out2")
for i in out2:
    print(i,i.shape)
print("out3")
for i in out3:
    print(i,i.shape)
print("out4")
for i in out4:
    print(i,i.shape)

b tensor([[0.0437, 0.1258, 0.7209, 0.8859],
        [0.8769, 0.8011, 0.3826, 0.7192],
        [0.9565, 0.0739, 0.6731, 0.1075],
        [0.6614, 0.6778, 0.5658, 0.3493],
        [0.4624, 0.9869, 0.3730, 0.8749],
        [0.5305, 0.5202, 0.5063, 0.7418],
        [0.2648, 0.7562, 0.9854, 0.9817],
        [0.2781, 0.1754, 0.6579, 0.6208],
        [0.7241, 0.2751, 0.7968, 0.1133],
        [0.9145, 0.2372, 0.5271, 0.4660]])
out1
tensor([[0.0437, 0.1258, 0.7209, 0.8859],
        [0.8769, 0.8011, 0.3826, 0.7192],
        [0.9565, 0.0739, 0.6731, 0.1075]]) torch.Size([3, 4])
tensor([[0.6614, 0.6778, 0.5658, 0.3493],
        [0.4624, 0.9869, 0.3730, 0.8749],
        [0.5305, 0.5202, 0.5063, 0.7418]]) torch.Size([3, 4])
tensor([[0.2648, 0.7562, 0.9854, 0.9817],
        [0.2781, 0.1754, 0.6579, 0.6208],
        [0.7241, 0.2751, 0.7968, 0.1133]]) torch.Size([3, 4])
tensor([[0.9145, 0.2372, 0.5271, 0.4660]]) torch.Size([1, 4])
out2
tensor([[0.0437, 0.1258, 0.7209],
        [0.8769, 0.8011, 0.3826],

# Tensor的填充操作
定义Tensor,并填充指定的数值
torch.full((2, 3), 3.14)
tensor([[ 3.14, 3.14, 3.14], [ 3.14, 3.14, 3.14]])

# 模型的保存/加载
torch.saves(state, dir) 保存/序列化
torch.load(dir) 加载模型
# 并行化
torch.get_num_threads():获得用于并行化CPU操作的OpenMP线程数
torch.set_num_threads(int):
设定用于并行化CPU操作的OpenMP线程数
# 重点Tensor与numpy的相互转换
torch.from_numpy(ndarry)
a.numpy() --> opencv导入图片得到numpy类型的数据，转化为Tensor,进行后续推理

In [52]:
import numpy as np
a = np.zeros([2,2])
out = torch.from_numpy(a)
print(out)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [53]:
import cv2
data = cv2.imread("test.png")
# print(data)
cv2.imshow("test",data)
tensor_data=torch.from_numpy(data)
'''
# 可以把数据放在GPU上
tensor_data1 = tensor_data.to(torch.device("cuda"))
#判断数据是否在GPU上
print(out.is_cuda)
# 因为GPU上的数据无法转化为numpy格式，所以需要再放入CPU上
tensor_data2 = tensor_data1.to(torch.device("cpu"))
'''
print(tensor_data)
out = torch.flip(tensor_data,dims=[0])
new_data = out.numpy()
cv2.imshow("test1",new_data)
cv2.waitKey(0)

tensor([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
        

-1

# 张量形状操作
掌握reshape()、squeze()、unsqueeze()、transpose() 、permute()、view()、contiguous()等函数使用
reshape()    :在不改变张量内容的前提下，对其形状做改变
unsqueeze()  :在指定的轴上增加一个维度为1的维度，升维（避免数据过于简单，模型欠拟合）
squeeze()    :在指定的轴上减少一个维度为1的维度，降维
transpose()  :一次只能交换2个维度
permute()    :一次可以交换多个维度
view()       :只能用于修改连续的张量，连续的张量:内存中存储顺序和张量显示顺序相同。非连续张量：经过某些操作,如transpose、permute
contiguous() :把不连续的张量变为连续的张量,即基于张量显示的顺序，修改内存中的储存顺序。
is_contiguous():判断张量是否连续

In [69]:
# 1.定义张量
torch.manual_seed(24)
t1 = torch.randint(1,10,(2,3))
print(f"t:{t1},shape:{t1.shape},row:{t1.shape[0]},columns:{t1.shape[1]}or{t1.shape[-1]}")

t:tensor([[6, 9, 9],
        [2, 8, 7]]),shape:torch.Size([2, 3]),row:2,columns:3or3


In [70]:
# 2. 通过reshape()函数,把t1 → 3行2列,1行6列,6行1列.
t2 = t1.reshape(3,2)
print(f"t:{t2},shape:{t2.shape},row:{t2.shape[0]},columns:{t2.shape[1]}or{t2.shape[-1]}")
'''
在不改变张量内容的前提下
t:tensor([[6, 9, 9],
        [2, 8, 7]])
t:tensor([[6, 9],
        [9, 2],
        [8, 7]])
改变前后都是699287（变为一维）
'''


t:tensor([[6, 9],
        [9, 2],
        [8, 7]]),shape:torch.Size([3, 2]),row:3,columns:2or2


'\n在不改变张量内容的前提下\nt:tensor([[6, 9, 9],\n        [2, 8, 7]])\nt:tensor([[6, 9],\n        [9, 2],\n        [8, 7]])\n改变前后都是699287（变为一维）\n'

In [71]:
# 尝试通过reshape()函数,把t1 → 2行5列的结果.
"""
会报错，2*3!=2*5
"""

'\n会报错，2*3!=2*5\n'

In [72]:
# 2. 定义函数,演示:unsqueeze()函数,squeeze()函数.
print(t1,t1.shape)
t2 = t1.unsqueeze(0)
print(f"t:{t2},shape:{t2.shape}")
print("--------------")
t3 = t1.unsqueeze(2)
print(f"t:{t3},shape:{t3.shape}")
"""
t4 = t1.unsqueeze(3)
print(f"t:{t4},shape:{t4.shape}")
索引溢出，报错
"""

tensor([[6, 9, 9],
        [2, 8, 7]]) torch.Size([2, 3])
t:tensor([[[6, 9, 9],
         [2, 8, 7]]]),shape:torch.Size([1, 2, 3])
--------------
t:tensor([[[6],
         [9],
         [9]],

        [[2],
         [8],
         [7]]]),shape:torch.Size([2, 3, 1])


'\nt4 = t1.unsqueeze(3)\nprint(f"t:{t4},shape:{t4.shape}")\n索引溢出，报错\n'

In [73]:
#  3. 定义函数,演示: transpose()函数,permute()函数
t1 = torch.randint(1,10,size=(2,3,4))
print(f"t:{t1},shape:{t1.shape}")
# 转为（4,3,2）
t2 = t1.transpose(0,2)
t3 = t1.transpose(0,-1)
print(f"t:{t2},shape:{t2.shape}")
print("------------------")
print(f"t:{t3},shape:{t3.shape}")
'''
t2 t3 二者一样
'''
# t1转为（4,2,3）
t4 = t1.permute(2,0,1)
print(f"t:{t4},shape:{t4.shape}")

t:tensor([[[8, 5, 8, 4],
         [7, 4, 3, 9],
         [3, 6, 1, 4]],

        [[2, 8, 1, 2],
         [5, 7, 4, 3],
         [4, 6, 5, 8]]]),shape:torch.Size([2, 3, 4])
t:tensor([[[8, 2],
         [7, 5],
         [3, 4]],

        [[5, 8],
         [4, 7],
         [6, 6]],

        [[8, 1],
         [3, 4],
         [1, 5]],

        [[4, 2],
         [9, 3],
         [4, 8]]]),shape:torch.Size([4, 3, 2])
------------------
t:tensor([[[8, 2],
         [7, 5],
         [3, 4]],

        [[5, 8],
         [4, 7],
         [6, 6]],

        [[8, 1],
         [3, 4],
         [1, 5]],

        [[4, 2],
         [9, 3],
         [4, 8]]]),shape:torch.Size([4, 3, 2])
t:tensor([[[8, 7, 3],
         [2, 5, 4]],

        [[5, 4, 6],
         [8, 7, 6]],

        [[8, 3, 1],
         [1, 4, 5]],

        [[4, 9, 4],
         [2, 3, 8]]]),shape:torch.Size([4, 2, 3])


In [77]:
# 4. 定义函数,演示: view()函数,contiguous()函数,is_contiguous()函数.
torch.manual_seed(24)
t1 = torch.randint(1,10,size=(2,3))
print(f"t:{t1},shape:{t1.shape}")
print("1",t1.is_contiguous())
t2 = t1.view(3,2)
print(f"t:{t2},shape:{t2.shape}")
print("2",t2.is_contiguous())
t3 = t1.transpose(0,1)
print("3",t3.is_contiguous())
t4 = t3.contiguous()
print("4",t4.is_contiguous())
"""
只有方法is_contiguous()是True才可以用view,即使是False也可以被reshape代替
"""

t:tensor([[6, 9, 9],
        [2, 8, 7]]),shape:torch.Size([2, 3])
1 True
t:tensor([[6, 9],
        [9, 2],
        [8, 7]]),shape:torch.Size([3, 2])
2 True
3 False
4 True
