# tensor 的定义

In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


In [3]:
a = torch.Tensor(2,3)
print(a)
print(a.type())

tensor([[7.7202e+02, 1.9632e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.FloatTensor


In [4]:
a = torch.ones(2,2)
print(a)
print(a.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [5]:
a = torch.eye(2,2)
print(a)
print(a.type())

tensor([[1., 0.],
        [0., 1.]])
torch.FloatTensor


In [6]:
a = torch.zeros(2,2)
print(a)
print(a.type())

tensor([[0., 0.],
        [0., 0.]])
torch.FloatTensor


In [7]:
b = torch.Tensor(2,3)
a = torch.zeros_like(b)
print(a)
print(a.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [8]:
a = torch.ones_like(b)
print(a)
print(a.type())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [9]:
a = torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.9942, 0.9608, 0.6889],
        [0.7668, 0.7133, 0.7805]])
torch.FloatTensor


In [10]:
# 正态分布型
a = torch.normal(mean=0.0,std=torch.rand(5))
print(a)
print(a.type())

tensor([ 0.0842, -0.1482, -0.5504, -0.1200,  1.5757])
torch.FloatTensor


In [11]:
a=torch.rand(5)
print(a)
print(a.type())

tensor([0.6759, 0.0924, 0.4618, 0.0596, 0.7534])
torch.FloatTensor


In [12]:
a=torch.rand(2,3)
print(a)
print(a.type())

tensor([[0.1396, 0.9997, 0.9126],
        [0.1333, 0.8808, 0.6966]])
torch.FloatTensor


In [13]:
# 均匀分布
a = torch.Tensor(2,2).uniform_(-1,1)
print(a)
print(a.type())

tensor([[-0.3950,  0.9461],
        [-0.0848,  0.3573]])
torch.FloatTensor


In [14]:
# 序列生成
# 从0到10，以步长 3 递增，直到小于 11 的数字序列
a = torch.arange(0,11,3)
print(a)
print(a.type())

tensor([0, 3, 6, 9])
torch.LongTensor


In [15]:
# 2到10之间取等间隔的4个数
a = torch.linspace(2,10,4)
print(a)
print(a.type())

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
torch.FloatTensor


In [16]:
# 对样本进行随机打乱
a = torch.randperm(5)
b = torch.randperm(10)
print("a:",a)
print("b:",b)
print("a.type():",a.type())
print("b.type():",b.type())

a: tensor([1, 4, 0, 2, 3])
b: tensor([8, 1, 7, 2, 0, 3, 5, 4, 9, 6])
a.type(): torch.LongTensor
b.type(): torch.LongTensor


# tensor 属性
每一个Tensor都有数据类型（torch.dtype）和设备（torch.device）、内存布局（torch.layout)这三个属性。设备：在CPU还是在个GPU（cuda:0,1,2...)内存布局：是稠密（在内存中表示的是一块连续的存储空间）还是稀疏（在内存中表示的不是一块连续的存储空间，而是由多个不连续的存储空间组成的）

In [17]:
# 创建一个稠密张量并指定数据类型、设备和内存布局
a = torch.tensor([1,2,3],dtype=torch.float32,device=torch.device('cpu'))
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


## 创建一个稀疏张量
坐标值（indices）和对应的值（values）

In [18]:
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor


In [19]:
# 转成稠密张量打印
indices = torch.tensor([[1,2,3],[1,2,3]])
values = torch.tensor([3,4,5],dtype=torch.int64)
x = torch.sparse_coo_tensor(indices,values,[3,4])
print(x)
print(x.type())
y = torch.sparse_coo_tensor(indices,values,[3,4]).to_dense()
print(y)
print(y.type())

tensor(indices=tensor([[1, 2, 3],
                       [1, 2, 3]]),
       values=tensor([3, 4, 5]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor
tensor([[0, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 0]])
torch.LongTensor


# tensor 算术运算

In [20]:
# add or sub
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a+b:",a+b)
print("a.add(b):",a.add(b))
print("torch.add(a,b):",torch.add(a,b))
print("a.add_(b):",a.add_(b))
print("a:",a)

a: tensor([[0.0491, 0.2932, 0.2430],
        [0.3472, 0.0843, 0.8478]])
b: tensor([[0.3671, 0.6453, 0.6468],
        [0.0353, 0.5301, 0.1886]])
a+b: tensor([[0.4162, 0.9385, 0.8898],
        [0.3825, 0.6144, 1.0364]])
a.add(b): tensor([[0.4162, 0.9385, 0.8898],
        [0.3825, 0.6144, 1.0364]])
torch.add(a,b): tensor([[0.4162, 0.9385, 0.8898],
        [0.3825, 0.6144, 1.0364]])
a.add_(b): tensor([[0.4162, 0.9385, 0.8898],
        [0.3825, 0.6144, 1.0364]])
a: tensor([[0.4162, 0.9385, 0.8898],
        [0.3825, 0.6144, 1.0364]])


In [21]:
# mul 乘（形状要相同）
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:",a)
print("b:",b)
print("a*b:",a*b)
print("a.mul(b):",a.mul(b))
print("torch.mul(a,b):",torch.mul(a,b))
print("a.mul_(b):",a.mul_(b))
print("a:",a)

a: tensor([[0.7738, 0.1395, 0.9719],
        [0.9513, 0.4373, 0.8785]])
b: tensor([[0.2992, 0.7698, 0.1789],
        [0.9580, 0.0300, 0.0561]])
a*b: tensor([[0.2316, 0.1074, 0.1739],
        [0.9113, 0.0131, 0.0493]])
a.mul(b): tensor([[0.2316, 0.1074, 0.1739],
        [0.9113, 0.0131, 0.0493]])
torch.mul(a,b): tensor([[0.2316, 0.1074, 0.1739],
        [0.9113, 0.0131, 0.0493]])
a.mul_(b): tensor([[0.2316, 0.1074, 0.1739],
        [0.9113, 0.0131, 0.0493]])
a: tensor([[0.2316, 0.1074, 0.1739],
        [0.9113, 0.0131, 0.0493]])


In [28]:
# pow
a = torch.Tensor([1,2])
print("a**3:",a**3)
print("a.pow(3):",a.pow(3))
print("torch.pow(a,3):",torch.pow(a,3))
print("a.pow_(3):",a.pow_(3))

a**3: tensor([1., 8.])
a.pow(3): tensor([1., 8.])
torch.pow(a,3): tensor([1., 8.])
a.pow_(3): tensor([1., 8.])


In [29]:
# exp log sqrt
a = torch.tensor([1,2],dtype=torch.float32)
print("a.exp():",a.exp())
print("a.exp_():",a.exp_())
print("torch.exp(a):",torch.exp(a))
print("torch.exp_(a):",torch.exp_(a))

a.exp(): tensor([2.7183, 7.3891])
a.exp_(): tensor([2.7183, 7.3891])
torch.exp(a): tensor([  15.1543, 1618.1781])
torch.exp_(a): tensor([  15.1543, 1618.1781])


# tensor 矩阵运算

In [23]:
# matmul
a = torch.rand(2,3)
b = torch.rand(3,2)
print("a@b:",a@b)
print("a.matmul(b):",a.matmul(b))
print("torch.matmul(a,b):",torch.matmul(a,b))
print("a.matmul(b):",a.mm(b))
print("torch.matmul(a,b):",torch.mm(a,b))

a@b: tensor([[0.7606, 0.1839],
        [1.5629, 0.7770]])
a.matmul(b): tensor([[0.7606, 0.1839],
        [1.5629, 0.7770]])
torch.matmul(a,b): tensor([[0.7606, 0.1839],
        [1.5629, 0.7770]])
a.matmul(b): tensor([[0.7606, 0.1839],
        [1.5629, 0.7770]])
torch.matmul(a,b): tensor([[0.7606, 0.1839],
        [1.5629, 0.7770]])


# 高维tensor

In [27]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(a.matmul(b).shape)
# torch.Size([1, 2, 3, 3])

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
torch.Size([1, 2, 3, 3])


# in-place 操作
形如 x = x + y 不产生新的变量，还有上面的add_ sub_ mul_ pow_等等

# 广播机制
需要满足的两个条件：
1. 每个张量至少有一个维度
2. 两个张量的维度从最右边开始逐个比较，最右侧维度需要相等，前面维度用1补齐，最终维度：两个张量每一维二者取最大
第13个视频 6:30秒